name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install NASM
      run: |
      	 sudo apt-get update
	 sudo apt-get install -y nasm

    - name: make
      run: make
    - name: make test
      run: make test
    - name: make examples
      run: make examples
